r1 = int(input("Enter the run scored by player 1 - "))
r2 = int(input("Enter the run scored by player 2 - "))
r3 = int(input("Enter the run scored by player 3 - "))
s_rate1 = ((r1*100)/60)
s_rate2 = ((r2*100)/60)
s_rate3 = ((r3*100)/60)
print("\n    STRIKE RATE  \n")
print("strike rate of player 1 is :- ",s_rate1)
print("strike rate of player 2 is :- ",s_rate2)
print("strike rate of player 3 is :- ",s_rate3)
print("\nrun scored by player 1 in more 60 balls is :- ",r1*2)
print("run scored by player 2 in more 60 balls is :- ",r2*2)
print("run scored by player 3 in more 60 balls is :- ",r3*2)
print("\nmaximum no of sixes player 1 could hit is = ",r1//6)
print("maximum no of sixes player 2 could hit is = ",r2//6)
print("maximum no of sixes player 3 could hit is = ",r3//6)
